sudo: required

language: php
php:
- '7.1.9'

branches:
  only:
  - master

# travis runtime environment from here or settings. : https://docs.travis-ci.com/user/environment-variables/
env:
  global:
  - ZIP_FILE="php-$TRAVIS_BUILD_NUMBER-$TRAVIS_COMMIT.zip"

  # travis-ci secure doc : https://docs.travis-ci.com/user/encryption-keys/
  # before install travis , first install ruby & gem
  # $ gem install travis
  # $ travis encrypt SOMEVAR="secretvalue"

  # AWS_ACCESS_KEY_ID_DEV
  - secure: ""
  # AWS_SECRET_ACCESS_KEY_DEV
  - secure: ""
  # AWS_ACCESS_KEY_ID_STG
  - secure: ""
  # AWS_SECRET_ACCESS_KEY_STG
  - secure: ""
  # AWS_ACCESS_KEY_ID_PROD , value : AKI....QMQ
  - secure: "uYRgoU6aB/BP0vD1oFLVFWoPGuqXy1NdnGLuldBgDQvDiSNV6YfBrT+BTwPtByi+mprcg8o2S2x5eOHNBFQXBg8VGiwouA5JbrbOc2H5OhRCOLFRM/L0+8tUyfwOjuVWcM+RLoCx96eOjycm9/1Sc5zHJNJorV/fFy31csp6VRu8x7PhdisdFv4+87MHCT/jgzV2UPFOLXyntikWWZRHaIDFX2QeSlhgzDZZ1CPTFxn5F6c5FxRtY13kycswwl/7+nFdevshlt8lOCvZpined54lmMMXsq6Z/3/FTII7FP7qYfpIbuABa6hcEPNdwb4eDas4Hh8JTRQQZuL+9mhYIWkCakK6dvN4HaEOrdi6nm2vytVLQHsHHF5S/tjZgqXavdouFrlN3X94SkXXxQ2t8oKSjwHRJyln1kBxDd3/TR4s6GtRPF1Az6Q0x3CFAPkP62VUw10OyWRPCfzgDjMGEg0nphxsAdpuB6kIsDD9jL8mGzU1FZJi7SC8iPdc9fqplOyVfAxGAZgfBzX0d89/YZOoXb6n5bmyD05gpzQ0VWTXEYHccTzScq6h+7gixv+bbnOPA/XNlaqV567LMH2GAtvsVVS6e1g/m+KTbWTO5vV34Um/4cYWsiwzjg+pN2kGJXDvDCNkCvq4xJEFf2K1Meh/l61KgGE63cj59YXJ4cE="
  # AWS_SECRET_ACCESS_KEY_PROD
  - secure: "HZVEDaiJ95fQQJ0kGxhfG9XkvxEbSTofk/6LT/VtFXhZj8p8C4WdxO8eCCvDMTtJGF1krL0iDQKy2VhizsNwC7AgUDTRbpj7ZaWlqG392IU5B+qaW6qTThvr7yDgxl9zYs07oxvhhr73SZdDTep9Il2QtoNFuH5C/HxIo7hVGw0zawD4ouVmJMet/gScoDrCGSoj3KiKK0/4PML6GMbjZvilcaBOupgWrpU3WKJOp8RIi3G1jZwhtCbfyI8zkTnYIvQfnh3ATOYEnyCjUtgH5N+uI9x70XJuhPzS9mHiee4+SmPSoaCSUSpUesBeA/kqHpDmMKDpj+5BswOWUZoH9yOsAcYkIgEg145Ndl1HCJ4k1mVQvM6Ad4SGThqHWzgK53DT/2Di/VFfloqEuPPl17VS8aGal8yeYZNP+pHZZ9WhgLxFpkS1+mziAZiwsqOuGKihb3lVAzptlIEUP1tnV6lkcpaPFVKDX/ROlJvOBFe2hIw1rBR5oH8TIUuD+BKY1gBFjRqEX4XBKZCQuUkFz1/2TfBwIfvudHMKkrMk/WcpfBWosauRwFDyb8fNqTaH6F3LG8Ex9ADtL8i3Bt0MxGNqXP99vSIgVGF2eyjWDUnE/yv5eS1Pccf7mAx3/KBq4X2XaZf/CZ5/OUwJzWMGFMCllPNUvlLH4ikibY0cS/w="
  
  # global variables
  - AWS_ACCESS_KEY_ID=''
  - AWS_SECRET_ACCESS_KEY=''
  - AWS_REGION='ap-northeast-1'
  - CODEDEPLOY_APP_NAME=''
  - CODEDEPLOY_GROUP=''


# notification - https://docs.travis-ci.com/user/notifications
# notifications:
#   email:
#     recipients:
#       - one@example.com
#       - other@example.com
#     on_success: never # default: change
#     on_failure: always # default: always
# integration to slack , setup on slack travis-ci app
notifications:
  email:
    on_failure: always
    on_success: never
  slack:
    rooms:
    - secure: "GLU8vsJV/6PjuRJLsQi5dE878x/KCZpc0ns+/jGZKRavqJ9xhiWTLAlQ2eGoiEoYD9vUwKTeyVoW2fxHaSw7IlPAzi/m3QZDcrSgdkvJVEJsslG8P7h42mmi04rsu5gHi+on7rl/RyZLsvSl9gw9LX8WPm0fCDgxjgGolvcIq9amCk6bTj5292rV6WEsjfEGWLFKnH1gtIzr4E4xzV0lOBzsiSogQPUGH1S4H9Oi6x2OXPqUDsMcVm7miv77LhgY2kXlIkt0Bp5iKHI8QdgLl2pqrCV+o75oTRzT/y2+So+ZSuxHYTmmglsgzWh6zFpkrZSpJeJxJVIpwYLBohI5J87/dyl3eTpvt7bnxYKf6ICePvemg+w54KHstBt9GY2GBKwu1NGXBEXl2SkDi9R8mgiAVWUUt/GxbVnBQ6aWDLIoo9J+Y3knuPKJB44axcpQ0nkjIeLO6EY6ixQy4vkeQXTTYtLS+03QR4CEpZvmsxuRgLQ1IuGQa5jAPUwUZwsF5l4QAisD5dLQgMhAjj4IAHUHWoNiRGWet5GCAN7f/WQVJu/CEv+P/yKJTrAOGXph1D868B5eqTo9AwssGj8t9bR2ZaSzcViHXJWs+fPZXLeFaLw8B5ZDppRfW5wpjcuX9T+d4kpSi4h5pG0loFs1uPFWu6jX3F4by59SSGjMf+k="
    
cache:
  directories:
  - $COMPOSER_CACHE_DIR
  - $HOME/.composer/cache




# build lifecycle - https://docs.travis-ci.com/user/customizing-the-build/
# (OPTIONAL) Install apt addons
# (OPTIONAL) Install cache components
# before_install
# install
# before_script
# script
# (OPTIONAL) before_cache (for cleaning up cache)
# after_success or after_failure
# (OPTIONAL) before_deploy
# (OPTIONAL) deploy
# (OPTIONAL) after_deploy
# after_script

# set -e : when error stop build.
before_install:
- set -e
- echo `date +"%Y-%m-%d %H:%M:%S"`
- echo $TRAVIS_BRANCH
- if [[ $TRAVIS_BRANCH == "dev" ]]; then
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV;
    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV;
    S3_BUCKET='';
    CODEDEPLOY_APP='';
    CODEDEPLOY_GROUP='';
  fi
- if [[ $TRAVIS_BRANCH == "staging" ]]; then
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_STG;
    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_STG;
    S3_BUCKET='';
    CODEDEPLOY_APP='';
    CODEDEPLOY_GROUP='';
  fi
- if [[ $TRAVIS_BRANCH == "master" ]]; then
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PROD;
    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PROD;
    S3_BUCKET='arn:aws:s3:::demo-kathyliu-20200117aaaaaaaaaaa';
    CODEDEPLOY_APP='Workshop-20200117-EC2-CodeDeploy';
    CODEDEPLOY_GROUP='ec2';
  fi


# put testing scripts here
script:
- echo 'script step...'

before_deploy:
- cd "$TRAVIS_BUILD_DIR";
  mkdir "$TRAVIS_BUILD_DIR/zip";
  zip -r "$TRAVIS_BUILD_DIR/zip/$ZIP_FILE" *


deploy:
- provider: S3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_REGION
  local_dir: $TRAVIS_BUILD_DIR/zip
  bucket: $S3_BUCKET
  skip_cleanup: true
  on:
    all_branches: true

- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_REGION
  bucket: $S3_BUCKET
  key: $ZIP_FILE
  bundle_type: zip
  application: $CODEDEPLOY_APP
  deployment_group: $CODEDEPLOY_GROUP
  wait_until_deployed: true
  on:
    all_branches: true
